<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>https://www.saucedemo.com/inventory-item.html?id=4</description>
   <name>DescricaoObjetoBolsa</name>
   <tag></tag>
   <elementGuidId>67e20a84-cc33-40c4-8059-0c472a13a39a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='inventory_details_desc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
