<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>https://www.saucedemo.com/inventory-item.html?id=4</description>
   <name>TituloObjetoBolsa</name>
   <tag></tag>
   <elementGuidId>cbbc656e-6599-4b03-85d6-2683a74a16ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='inventory_details_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
