<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>https://s1.demo.opensourcecms.com/s/44</description>
   <name>SiteOrangeExemplo1</name>
   <tag></tag>
   <elementGuidId>6374d600-4433-405d-a5f6-70d6af50e621</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>&quot;//input[@id='organization_province']&quot;</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
