<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>OpcaoMENUDressesAutoPract</name>
   <tag></tag>
   <elementGuidId>cb2031be-e9e4-4530-a97a-67d55e0a6b75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>&quot;//div[@id='block_top_menu']/ul/li/a[@title='Dresses']&quot;</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
